routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\NewsController;
use App\Http\Controllers\Admin\SubCategoryController;
use App\Http\Controllers\Frontend\FrontendController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
Route::get('/',[FrontendController::class, 'index'])->name('front.index');
Route::get('/single-news',[FrontendController::class, 'single_news'])->name('front.single_news');
//Route::get('/add-slug',[FrontendController::class, 'add_slug']);
Route::group(['prefix'=> 'dashboard','middleware'=>'auth'],function(){

   Route::get('/', [DashboardController::class, 'index'])->name('dashboard.index');
   Route::get('get-sub-categories/{id}',[SubCategoryController::class,'get_sub_categories']);
    /*
   Route::get('/categories',[CategoryController::class,'index'])->name('categories.index');
   Route::get('/categories/create',[CategoryController::class,'create'])->name('categories.create');
   Route::post('/categories',[CategoryController::class,'store'])->name('categories.store');
   Route::get('/categories/{category}',[CategoryController::class,'show'])->name('categories.show');
   Route::get('/categories/{category}/edit',[CategoryController::class,'edit'])->name('categories.edit');
   Route::put('/categories/{category}',[CategoryController::class,'update'])->name('categories.update');
   Route::delete('/categories/{category}',[CategoryController::class,'destroy'])->name('categories.destroy');
*/
   Route::resource('categories',CategoryController::class);
   Route::resource('sub-categories', SubCategoryController::class);
   Route::resource('news', NewsController::class);
});
Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/{slug}',[FrontendController::class, 'category'])->name('front.category');

app/Models/SubCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @method static create(array $data)
 * @method static orderBy(string $string, string $string1)
 * @method static select(string $string, string $string1)
 * @method static pluck(string $string, string $string1)
 * @method static where(string $string, string $slug)
 */
class SubCategory extends Model
{
    use HasFactory;
    protected $guarded = [];
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function user()
    {
        return $this->belongsTo(user::class);
    }

    public function news(): HasMany
    {
        return $this->hasMany(News::class);
    }
}

app/Http/Controllers/Admin/SubCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use App\Models\SubCategory;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;

class SubCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $subCategories = SubCategory::orderBy('order_by', 'asc')->with('category', 'user')->paginate(30);
        return \view('dashboard.pages.sub_category.index', compact('subCategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        $categories = Category::pluck('name', 'id');
        return view('dashboard.pages.sub_category.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'category_id' => 'required',
            'status' => 'required',
            'order_by' => 'required',
        ]);
        $data = $request->all();
        $data['user_id'] = Auth::user()->id;
        SubCategory::create($data);
        session()->flash('msg', 'Sub Category Create Successfully');
        return redirect()->route('sub-categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param SubCategory $subCategory
     * @return Application|Factory|View
     */
    public function show(SubCategory $subCategory)
    {
        $subCategory->load('category', 'user');
        return view('dashboard.pages.sub_category.show', compact('subCategory'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param SubCategory $subCategory
     * @return Application|Factory|View
     */
    public function edit(SubCategory $subCategory)
    {
        $categories = Category::pluck('name', 'id');
        return \view('dashboard.pages.sub_category.edit', compact('subCategory', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param SubCategory $subCategory
     * @return RedirectResponse
     */
    public function update(Request $request, SubCategory $subCategory)
    {
        $request->validate([
            'name' => 'required',
            'order_by' => 'required',
            'status' => 'required']);
        session()->flash('msg', 'Category Updated Successfully');
        $subCategory->update($request->all());
        return redirect()->route('sub-categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param SubCategory $subCategory
     * @return RedirectResponse
     */
    public function destroy(SubCategory $subCategory)
    {
        $subCategory->delete();
        session()->flash('msg', 'Sub Category Deleted Successfully');
        return redirect()->route('sub-categories.index');
    }

    /**
     * @param $id
     * @return JsonResponse
     */
    public function get_sub_categories($id): JsonResponse
    {
       $subCategories = SubCategory::select('name','id')->where('category_id',$id)->get();
       return response()->json($subCategories);
    }
}

resources/views/dashboard/pages/sub_category/create.blade.php
@extends('dashboard.layout.master')
@section('page_title','Sub Category Create')
@section('content')
    <div class="row">
        <div class="col-12 col-lg-10 mx-auto">
            <div class="card">
                <div class="card-header"><h3 class="text-center">Create Sub Category</h3></div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                @if (session('msg'))
                    <div class="alert alert-success">
                        {{session('msg')}}
                    </div>
                @endif
                <div class="card-body">

                    {!! Form::open(['method'=>'post','route'=>'sub-categories.store']) !!}
                    @include('dashboard.pages.sub_category.form')
                    {!! Form::button('<i class="fas fa-plus mx-1"></i>Create',['type'=>'submit', 'class'=>'btn btn-success ps-2 mt-3 form-control']) !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/pages/sub_category/edit.blade.php
@extends('dashboard.layout.master')
@section('page_title','Sub Category Edit')
@section('content')
    <div class="row">
        <div class="col-12 col-lg-10 mx-auto">
            <div class="card">
                <div class="card-header"><h3 class="text-center">Edit Sub Category</h3></div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                @if (session('msg'))
                    <div class="alert alert-success">
                        {{session('msg')}}
                    </div>
                @endif
                <div class="card-body">

                    {!! Form::model($subCategory,[ 'method'=>'put','route'=>['sub-categories.update',$subCategory->id]]) !!}
                    @include('dashboard.pages.sub_category.form')
                    {!! Form::button('<i class="fas fa-plus mx-1"></i>Update',['type'=>'submit', 'class'=>'btn btn-success ps-2 mt-3 form-control']) !!}
                    {!! Form::close() !!}
                    <a href="{{route('sub-categories.index')}}" class="mt-3 form-control btn btn-warning ">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/pages/sub_category/form.blade.php
{!! Form::label('name','Sub Category Name',['class'=>'lead ps-2']) !!}
{!! Form::text('name',null,['class'=>'form-control','placeholder'=>'Insert Sub Category name']) !!}
{!! Form::label('category_id','Select Category',['class'=>'lead ps-2']) !!}
{!! Form::select('category_id',$categories,null,['class'=> 'form-control','placeholder'=>'Select Category']) !!}

{!! Form::label('order_by','Order By',['class'=>'lead ps-2']) !!}
{!! Form::number('order_by',null, ['class'=>'form-control','placeholder'=>'Insert Menu Order']) !!}
{!! Form::label('status','Status',['class'=>'lead ps-2']) !!}
{!! Form::select('status',['1'=>'Active','2'=>'Inactive'],null,['class'=>'form-control','placeholder'=>'Select Option']) !!}

resources/views/dashboard/pages/sub_category/index.blade.php
@extends('dashboard.layout.master')
@section('page_title','subCategory List')
@section('content')
    <div class="row">
        <div class="col-12 col-lg-12 mx-auto">
            <div class="card">
                <div class="card-header"><h3 class="text-center"> subCategory list</h3></div>

                @if (session('msg'))
                    <div class="alert alert-success">
                        {{session('msg')}}
                    </div>
                @endif

                <div class="card-body">
                    <table class="table table-responsive table-bordered table-striped text-center ">
                        <thead>
                        <tr class="text-center">
                            <th>Sl</th>
                            <th>Sub Category Name</th>
                            <th>Category Name</th>
                            <th>Order By</th>
                            <th>Stats</th>
                            <th>Create By</th>
                            <th>Create At</th>
                            <th>Update At</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @php
                            $sl = 1;
                        @endphp
                        @foreach($subCategories as $subCategory)

                            <tr>
                                <th>{{$sl++}}</th>
                                <th>{{$subCategory->name}}</th>
                                <th>{{$subCategory->category->name}}</th>
                                <th>{{$subCategory->order_by}}</th>
                                <th>{!!$subCategory->status == 1 ? '<span class="text-success">Active</span>':'<span class="text-danger">Inactive</span>'!!}</th>
                                <th>{{$subCategory->user->name}}</th>
                                <th>{{$subCategory->created_at->toDayDateTimeString()}}</th>
                                <th>{{$subCategory->updated_at == $subCategory->created_at ? 'Not Updated':$subCategory->updated_at->toDayDateTimeString()}}</th>
                                <th class="d-flex justify-content-between">
                                    <a href="{{route('sub-categories.show', $subCategory->id)}}"> <button class="btn btn-success btn-sm mx-2 text-white"><i class="fas fa-eye"></i></button></a>
                                    <a href="{{route('sub-categories.edit',$subCategory->id)}}"><button class="btn btn-warning btn-sm mx-2"><i class="fas fa-edit"></i></button></a>
                                    {!! Form::open(['method'=>'delete','route'=>['sub-categories.destroy',$subCategory->id]]) !!}
                                    {!! Form::button('<i class="fas fa-trash"></i>',['type'=>'submit', 'class'=>'btn btn-danger btn-sm mx-2','onclick'=>'return confirm("Age you Sure")']) !!}
                                    {!! Form::close() !!}
                                </th>
                                @endforeach
                            </tr>
                        </tbody>
                    </table>
                    {{ $subCategories->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/pages/sub_category/show.blade.php
@extends('dashboard.layout.master')
@section('page_title','Category Details')
@section('content')
    <div class="row">
        <div class="col-12 col-lg-7 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-center"> Sub Category Details</h3>
                </div>
                <div class="card-body">
                    <table class="table table-responsive table-bordered table-striped text-center ">
                        <tr>
                            <th>Sub Name</th>
                            <td>{{$subCategory->name}}</td>
                        </tr><tr>
                            <th>Category Name</th>
                            <td>{{$subCategory->category->name}}</td>
                        </tr>
                        <tr>
                            <th>Order By</th>
                            <td>{{$subCategory->order_by}}</td>
                        </tr>
                        <tr>
                            <th>Status</th>
                            <td>{!! $subCategory->status == 1 ? '<span class="text-success">Active</span>': '<span class="text-danger">Inactive</span>' !!}</td>
                        </tr>
                        <tr>
                            <th>Crated At</th>
                            <td>{{$subCategory->created_at->toDayDateTimeString()}}</td>
                        </tr>
                        <tr>
                            <th>Updated At</th>
                            <td>{{$subCategory->updated_at == $subCategory->created_at ?'Not Updated Yet': $subCategory->updated_at->toDayDateTimeString()}}</td>
                        </tr>
                        <tr>
                            <th>Create By</th>
                            <td>{{$subCategory->user->name}}</td>
                        </tr>

                    </table>
                    <div class="card-link g-5">
                        <a href="{{route('sub-categories.index')}}" class="btn btn-success">Back</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection